#!/bin/sh
#
# run mcnp test job
#
# mcnp   input file = balltest
# radsrc input file = problem.in
#

#....delete previous mcnpx output files
/bin/rm outp runtpe 2> /dev/null

#....location of mcnpx executable that contains RadSrc source.F
mcnp=/usr/gapps/dmc/mcnp/140.radsrc_dev/Source/src/mcnp5

#....location of mcnpx data files
export DATAPATH=/usr/gapps/dmc/mcnpx/data 

#....setup radsrc environment variables
source ../setup

#....run test job
$mcnp inp=balltest

#....compare to reference
diff outp outp.ref

